<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start_m1</name>
   <tag></tag>
   <elementGuidId>b8d81453-871a-43a2-bc83-5055653f36ab</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/programs/Program1/Course1/Module1/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-info</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default-modulesList&quot;)/div[@class=&quot;modules-list-wrap&quot;]/div[@class=&quot;modules-list row modules-list-2&quot;]/div[@class=&quot;col-sm-6 module-wrapper module-wrapper-list&quot;]/div[@class=&quot;module&quot;]/div[@class=&quot;module-body&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;btn btn-sm btn-info&quot;]</value>
   </webElementProperties>
</WebElementEntity>
