<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Next_module_page</name>
   <tag></tag>
   <elementGuidId>3e51401a-6782-4db6-99e9-2a77e43f94f9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default-modulePageToolbar&quot;)/div[@class=&quot;panel panel-default panel-module-page-toolbar&quot;]/div[@class=&quot;panel-heading text-right&quot;]/div[@class=&quot;btn-group pages&quot;]/a[@class=&quot;nextBtn btn enabled&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
